### ISSUE TITLE
code thief

### ISSUE THREAD

**Issue by Elliot2636** [summer-os/summer-mybatis#101]
I'm ashamed of you, thief, disrespectful to the original author

**Comment by Jzow** [comment]
you don't know much about open source

**Comment by kotlin2018** [comment]
> you don't know much about open source

I sincerely hope your project is cool

**Comment by kotlin2018** [comment]
> you don't know much about open source

I curse you for the coolness of this project

**Comment by Jzow** [comment]
You should make some contribution to rbatis instead of complaining about ignorance here because you don't know about open source. Out of courtesy, I will answer you for the last time. Open source itself provides more convenience for everyone. I don't care what developers choose to use. I don't pay for the coldness of this warehouse.

**Comment by kotlin2018** [comment]
Open source spirit is to copy other people's code like you? If you contribute to rbatis, you will contribute code directly to rbatis. Don't close the issues

**Comment by Jzow** [comment]
@kotlin2018 您是中国人吧，中国要是都是你这种自私自利的人我们永远都一直原地踏步，rabtis我也贡献过，但是少之又少，它只是解决了一部分的问题，换句话说我们都是用自己闲暇时间做开源项目无非都是学习，rabtis的维护者如果都是你这样的人，我真感到可悲，希望你不是rbatis作者本人，口口声声打着开源精神，要求别人一直向一个repo贡献

你真应该在rbatis仓库提一个issue下面放上支付宝 网银 甚至加密钱包地址，让大家来为你杰出而又伟大的贡献来买单
